language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install
# command to run tests
script:
  - python robot.py test
  - flake8 . 
  - black --check --diff .
